# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_courses.ui'
#
# Created: Tue Feb 11 19:47:14 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_select_courses(object):
    def setupUi(self, select_courses):
        select_courses.setObjectName(_fromUtf8("select_courses"))
        select_courses.resize(531, 585)
        self.layoutWidget = QtGui.QWidget(select_courses)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 180, 511, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.studied_layout = QtGui.QVBoxLayout(self.layoutWidget)
        self.studied_layout.setMargin(0)
        self.studied_layout.setObjectName(_fromUtf8("studied_layout"))
        self.studied_label = QtGui.QLabel(self.layoutWidget)
        self.studied_label.setObjectName(_fromUtf8("studied_label"))
        self.studied_layout.addWidget(self.studied_label)
        self.studied_table_widget = QtGui.QTableWidget(self.layoutWidget)
        self.studied_table_widget.setObjectName(_fromUtf8("studied_table_widget"))
        self.studied_table_widget.setColumnCount(5)
        self.studied_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.studied_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.studied_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.studied_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.studied_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.studied_table_widget.setHorizontalHeaderItem(4, item)
        self.studied_layout.addWidget(self.studied_table_widget)
        self.layoutWidget_2 = QtGui.QWidget(select_courses)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 320, 511, 171))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.could_select_layout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.could_select_layout.setMargin(0)
        self.could_select_layout.setObjectName(_fromUtf8("could_select_layout"))
        self.could_select_label = QtGui.QLabel(self.layoutWidget_2)
        self.could_select_label.setObjectName(_fromUtf8("could_select_label"))
        self.could_select_layout.addWidget(self.could_select_label)
        self.could_select_table_widget = QtGui.QTableWidget(self.layoutWidget_2)
        self.could_select_table_widget.setObjectName(_fromUtf8("could_select_table_widget"))
        self.could_select_table_widget.setColumnCount(8)
        self.could_select_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.could_select_table_widget.setHorizontalHeaderItem(7, item)
        self.could_select_layout.addWidget(self.could_select_table_widget)
        self.layoutWidget1 = QtGui.QWidget(select_courses)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 511, 161))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.selected_courses_layout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.selected_courses_layout.setMargin(0)
        self.selected_courses_layout.setObjectName(_fromUtf8("selected_courses_layout"))
        self.selected_courses_label = QtGui.QLabel(self.layoutWidget1)
        self.selected_courses_label.setObjectName(_fromUtf8("selected_courses_label"))
        self.selected_courses_layout.addWidget(self.selected_courses_label)
        self.selected_table_widget = QtGui.QTableWidget(self.layoutWidget1)
        self.selected_table_widget.setObjectName(_fromUtf8("selected_table_widget"))
        self.selected_table_widget.setColumnCount(6)
        self.selected_table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.selected_table_widget.setHorizontalHeaderItem(5, item)
        self.selected_courses_layout.addWidget(self.selected_table_widget)
        self.layoutWidget2 = QtGui.QWidget(select_courses)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 500, 202, 66))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.input_layout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.input_layout.setMargin(0)
        self.input_layout.setObjectName(_fromUtf8("input_layout"))
        self.courses_id_layout = QtGui.QHBoxLayout()
        self.courses_id_layout.setObjectName(_fromUtf8("courses_id_layout"))
        self.courses_id_label = QtGui.QLabel(self.layoutWidget2)
        self.courses_id_label.setObjectName(_fromUtf8("courses_id_label"))
        self.courses_id_layout.addWidget(self.courses_id_label)
        self.courses_id_lineedit = QtGui.QLineEdit(self.layoutWidget2)
        self.courses_id_lineedit.setObjectName(_fromUtf8("courses_id_lineedit"))
        self.courses_id_layout.addWidget(self.courses_id_lineedit)
        self.input_layout.addLayout(self.courses_id_layout)
        self.tea_id_layout = QtGui.QHBoxLayout()
        self.tea_id_layout.setObjectName(_fromUtf8("tea_id_layout"))
        self.tea_id_label = QtGui.QLabel(self.layoutWidget2)
        self.tea_id_label.setObjectName(_fromUtf8("tea_id_label"))
        self.tea_id_layout.addWidget(self.tea_id_label)
        self.tea_id_lineedit = QtGui.QLineEdit(self.layoutWidget2)
        self.tea_id_lineedit.setObjectName(_fromUtf8("tea_id_lineedit"))
        self.tea_id_layout.addWidget(self.tea_id_lineedit)
        self.input_layout.addLayout(self.tea_id_layout)
        self.layoutWidget3 = QtGui.QWidget(select_courses)
        self.layoutWidget3.setGeometry(QtCore.QRect(270, 520, 241, 41))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.select_courses_layout = QtGui.QHBoxLayout()
        self.select_courses_layout.setObjectName(_fromUtf8("select_courses_layout"))
        self.select_courses_button = QtGui.QPushButton(self.layoutWidget3)
        self.select_courses_button.setObjectName(_fromUtf8("select_courses_button"))
        self.select_courses_layout.addWidget(self.select_courses_button)
        self.drop_courses_button = QtGui.QPushButton(self.layoutWidget3)
        self.drop_courses_button.setObjectName(_fromUtf8("drop_courses_button"))
        self.select_courses_layout.addWidget(self.drop_courses_button)
        self.horizontalLayout.addLayout(self.select_courses_layout)
        self.refresh_button = QtGui.QPushButton(self.layoutWidget3)
        self.refresh_button.setObjectName(_fromUtf8("refresh_button"))
        self.horizontalLayout.addWidget(self.refresh_button)

        self.retranslateUi(select_courses)
        # QtCore.QMetaObject.connectSlotsByName(select_courses)

    def retranslateUi(self, select_courses):
        select_courses.setWindowTitle(_translate("select_courses", "选课窗口", None))
        self.studied_label.setText(_translate("select_courses", "已修课程", None))
        item = self.studied_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("select_courses", "课程号", None))
        item = self.studied_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("select_courses", "课程名", None))
        item = self.studied_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("select_courses", "学期", None))
        item = self.studied_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("select_courses", "学分", None))
        item = self.studied_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("select_courses", "成绩", None))
        self.could_select_label.setText(_translate("select_courses", "可选课程", None))
        item = self.could_select_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("select_courses", "课程号", None))
        item = self.could_select_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("select_courses", "课程名", None))
        item = self.could_select_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("select_courses", "教师号", None))
        item = self.could_select_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("select_courses", "教师名", None))
        item = self.could_select_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("select_courses", "学期", None))
        item = self.could_select_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("select_courses", "上课时间", None))
        item = self.could_select_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("select_courses", "学分", None))
        item = self.could_select_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("select_courses", "开课学院", None))
        self.selected_courses_label.setText(_translate("select_courses", "已选课程", None))
        item = self.selected_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("select_courses", "课程号", None))
        item = self.selected_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("select_courses", "课程名", None))
        item = self.selected_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("select_courses", "教师号", None))
        item = self.selected_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("select_courses", "教师姓名", None))
        item = self.selected_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("select_courses", "学期", None))
        item = self.selected_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("select_courses", "上课时间", None))
        self.courses_id_label.setText(_translate("select_courses", "课程编号:", None))
        self.tea_id_label.setText(_translate("select_courses", "教师号:    ", None))
        self.select_courses_button.setText(_translate("select_courses", "选课", None))
        self.drop_courses_button.setText(_translate("select_courses", "退课", None))
        self.refresh_button.setText(_translate("select_courses", "刷新", None))

